### ISSUE TITLE
version-bump-publish.yml - does not work with Protected Branches with status checks

### ISSUE THREAD

**Issue by shazron** [adobe/.github#3]
### Expected Behaviour

Works with branches with status checks.

### Actual Behaviour

Does not work with branches with status checks.

### Possible Workarounds

1. Enable force push, and update the workflow to force push (see Protected Branch settings screenshot below)
2. There's also `skip-checks: true` in a commit message (perhaps we can do a `git commit --amend` after the `npm version` command?) https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks

### Reproduce Scenario (including but not limited to)

Sample repo workflow error: https://github.com/adobe/generator-aio-app/runs/1763090447?check_suite_focus=true 
<img width="892" alt="Screenshot 2021-01-25 at 11 51 34 PM" src="https://user-images.githubusercontent.com/36107/105731423-5c05fb00-5f6a-11eb-9643-a47f941fc466.png">

### Protected Branch Settings

![Screen Shot 2021-01-25 at 11 52 06 PM](https://user-images.githubusercontent.com/36107/105731412-58727400-5f6a-11eb-8cb3-756101a8fae1.png)

**Comment by macdonst** [comment]
@shazron @purplecabbage I think I have a way around this issue. If we use the `adobe-bot` credentials we can have branch protection and automation. I've test driven it in the jwt-auth repo:

https://github.com/adobe/jwt-auth/commit/72997490401e99acd269a9c79129ba142063a632

and it worked great releasing a 1.0.1.

https://github.com/adobe/jwt-auth/actions/runs/778895700

If you think it is worthwhile I can make the changes to our existing workflows in this repo.

**Comment by shazron** [comment]
LGTM!
