### ISSUE TITLE
on-push-publish-to-npm.yml: 403 error

### ISSUE THREAD

**Issue by shazron** [adobe/.github#4]
When I publish I get a `403` error:
```
npm ERR! code E403
130
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@adobe%2fgenerator-aio-app - This package requires that publishers enable TFA and provide an OTP to publish. For more info, visit: https://go.npm.me/2fa-guide
131
npm ERR! 403 In most cases, you or one of your dependencies are requesting
132
npm ERR! 403 a package version that is forbidden by your security policy.
```

See: 
https://github.com/adobe/generator-aio-app/runs/1763294230?check_suite_focus=true

I have `ADOBE_BOT_NPM_TOKEN` as an Org secret.

**Comment by purplecabbage** [comment]
It is a requirement that the npm module be configured to allow publishing without OTP.

**Comment by shazron** [comment]
Basically, for now, we need this setting:
<img width="774" alt="Screenshot 2021-01-28 at 5 21 57 PM" src="https://user-images.githubusercontent.com/36107/106116859-5d633d80-618d-11eb-8bb2-4048249e93d7.png">
