### ISSUE TITLE
forks should not run publishing actions

### ISSUE THREAD

**Issue by purplecabbage** [adobe/.github#5]
Pushing to my own fork of and adobe repo modifies package.json, which in turn triggers the publish action.  I of course do not have the npm credentials in my repo's secrets, so the publish fails, but it would be better if it did not run at all.

This will require some research into how repo-forks might be created without also forking the workflows, or having the workflows somehow aware that they are fork .. or check for existence of required secrets before running install/test actions which are resource hogs.

**Comment by shazron** [comment]
I did something in this workflow where I checked for forks: https://github.com/adobe/aio-cli-plugin-doc/blob/33ffb99e36e0c2b067830f8e72adbdfb6252714f/src/generator/templates/.github/workflows/pr-approved.yml#L17-L34
