### ISSUE TITLE
Add new workflow npm publish on github release created

### ISSUE THREAD

**Issue by icaraps** [adobe/.github#6]
Similar to https://github.com/adobe/reactor-token-scripts-edge/blob/main/.github/workflows/npm-publish.yml, `npm publish` is handled by the github action but everything before which is only github related (version bump, update CHANGELOG, create github tag / release etc.) is handled by the committer.

**Comment by purplecabbage** [comment]
is this still required? How is this different than what we have?

**Comment by icaraps** [comment]
No it can be closed.
